[project]
name = "pktools"
version = "0.8.1"
description = "Modules de manipulation de pk et de tronçons"
readme = "README.md"
authors = [
    { name = "efbulle", email = "emmanuel.favrebulle@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "polars>=1.38.1",
]

[build-system]
requires = ["uv_build>=0.11.7,<0.12"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
